config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public#home"

  get '/browse', to: 'browse#browse', as: 'browse'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many_attached :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController

def browse
    @users = Account.where.not(id: current_account.id)
end

def approve
end

def disprove
end


end

app/controllers/public_controller.rb
class PublicController < ApplicationController

def home
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/browse/browse.html.erb
<ul id="slides">
<% @users.each_with_index do |user, index| %>
<div class="slide" data-id="<%= index %>">
    <li><%= user.first_name %></li>
</div>
<% end %>
</ul>



<button class="controls" id="decline">No</button>
<button class="controls" id="approve">Yes</button>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">© 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
          <li><a class="text-muted" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource name</a></li>
          <li><a class="text-muted" href="#">Another resource</a></li>
          <li><a class="text-muted" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Tinder Clone</h5>
  
  <% if account_signed_in? %>
  <nav class="my-2 my-md-0 mr-md-3">
  <%= link_to "Browse", browse_path, class: "text-dark mr-3" %>
  <%= link_to "My matches", "#", class: "text-dark mr-3" %>
  <%= link_to "Settings", "#", class: "text-dark" %>
  </nav>

  <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "btn btn-secondary mr-2" %>


  <% else %>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#">Features</a>
    <a class="p-2 text-dark" href="#">Pricing</a>
    <a class="p-2 text-dark" href="#">Support</a>
  </nav>
  <%= link_to "Sign In", new_account_session_path, class: "btn btn-secondary mr-2" %>
  <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinderclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/nav" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>